version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 9000:9000
      - 8000:80
    depends_on:
      - python

  python:
    build:
      context: ./python
    ports:
      - 8080:8080
